---
language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:stretch-slim
    - MOLECULE_DISTRO=debian:buster-slim
script:
  - export MOLECULE_DISTRO=${MOLECULE_DISTRO}
  - travis_wait 30 pipenv run molecule test -s binaries
  - travis_wait 30 pipenv run molecule test -s sources

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
