---

- name: NODEJS | Extract sources package
  unarchive:
    src: "{{ nodejs_sources_url }}"
    dest: "{{ nodejs_install_path }}"
    extra_opts: ['--strip-components=1']
    remote_src: true
    owner: "{{ nodejs_user }}"
    group: "{{ nodejs_group }}"

- name: NODEJS | Build sources
  command: "chdir={{ nodejs_install_path }} {{ item }}"
  with_items:
    - ./configure
    - make
    - make install
  tags:
    skip_ansible_lint

- name: NODEJS | Link node binary
  file:
    src: "{{ nodejs_install_path }}/out/Release/node"
    dest: "/usr/bin/node"
    state: link

- name: NODEJS | Link npm binary
  file:
    src: "{{ nodejs_install_path }}/deps/npm/bin/npm"
    dest: "/usr/bin/npm"
    state: link

- name: NODEJS | Link npx binary
  file:
    src: "{{ nodejs_install_path }}/deps/npm/bin/npx"
    dest: "/usr/bin/npx"
    state: link
  when: nodejs_install_npx
