---

- name: NODEJS | Download sources package
  get_url:
    url: "{{ nodejs_sources_url }}"
    dest: "{{ nodejs_tmp }}"

- name: NODEJS | Extract sources package
  unarchive:
    copy: no
    src: "{{ nodejs_tmp }}/{{ nodejs_sources_package }}"
    dest: "{{ nodejs_tmp }}"

- name: NODEJS | Build sources
  command: "chdir={{ nodejs_tmp }}/node-v{{ nodejs_version }} {{item}}"
  with_items:
    - ./configure
    - make
    - make install
  tags:
    skip_ansible_lint

- name: NODEJS | Copy files
  command: "cp -R {{ nodejs_tmp }}/node-v{{ nodejs_version }}/. {{ nodejs_root_path }}/"
  tags:
    skip_ansible_lint

- name: NODEJS | Link node binary
  file:
    src: "{{ nodejs_root_path }}/out/Release/node"
    dest: "/usr/bin/node"
    state: link

- name: NODEJS | Link npm binary
  file:
    src: "{{ nodejs_root_path }}/deps/npm/bin/npm"
    dest: "/usr/bin/npm"
    state: link
