---

- name: NODEJS | Extract binaries package
  unarchive:
    src: "{{ nodejs_binaries_url }}"
    dest: "{{ nodejs_install_path }}"
    extra_opts: ['--strip-components=1']
    remote_src: true
    owner: "{{ nodejs_user }}"
    group: "{{ nodejs_group }}"

- name: NODEJS | Link binaries
  file:
    src: "{{ nodejs_install_path }}/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  with_items:
    - node
    - npm
    - npx
