---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: node-stretch
    hostname: node
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
    groups:
      - node
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'

provisioner:
  name: ansible

scenario:
  name: binaries

verifier:
  name: ansible
  directory: ./tests
